### ISSUE TITLE
Compilation issue on ubuntu 

### ISSUE THREAD

**Issue by sanilraut** [twitter/vireo#4] opened 2017-12-16 21:49 UTC
Hi, 
I get the following issue while trying to build: 

./configure --prefix=$PREFIX
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking whether g++ supports C++14 features by default... no
checking whether g++ supports C++14 features with -std=gnu++14... yes
checking whether C++ compiler accepts -fvisibility=hidden... yes
checking for lsmash_free in -llsmash... yes
checking for aacDecoder_Open in -lfdk-aac... yes
checking for ogg_packet_clear in -logg... yes
checking for pthread_create in -lpthread... yes
checking for vorbis_block_init in -lvorbis... yes
checking for vorbis_encode_init in -lvorbisenc... yes
checking for vpx_free in -lvpx... no
checking for _ZN8mkvmuxer10AudioTrackC1EPj in -lwebm... no
checking for deflate in -lz... yes
checking how to run the C++ preprocessor... g++ -std=gnu++14 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for getcwd... yes
checking for memset... yes
checking for mkdir... yes
checking for munmap... yes
checking for sqrt... yes
checking for strrchr... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -std=gnu++14 -E
checking for ld used by g++ -std=gnu++14... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -std=gnu++14 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -std=gnu++14 option to produce PIC... -fPIC -DPIC
checking if g++ -std=gnu++14 PIC flag -fPIC -DPIC works... yes
checking if g++ -std=gnu++14 static flag -static works... no
checking if g++ -std=gnu++14 supports -c -o file.o... yes
checking if g++ -std=gnu++14 supports -c -o file.o... (cached) yes
checking whether the g++ -std=gnu++14 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vireo.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in ../imagecore (/media/sanil/SanilED/Video/Twitter/vireo/vireo/../imagecore)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/media/sanil/SanilED/Video/Twitter/install'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for jpeg_mem_src in -ljpeg... no
checking for png_create_read_struct in -lpng16... no
checking for WebPDecode in -lwebp... yes
checking for cmsCloseProfile in -llcms2... no
checking whether C++ compiler accepts -msse4.1... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for ld used by g++ -std=gnu++11... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -std=gnu++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -std=gnu++11 option to produce PIC... -fPIC -DPIC
checking if g++ -std=gnu++11 PIC flag -fPIC -DPIC works... yes
checking if g++ -std=gnu++11 static flag -static works... yes
checking if g++ -std=gnu++11 supports -c -o file.o... yes
checking if g++ -std=gnu++11 supports -c -o file.o... (cached) yes
checking whether the g++ -std=gnu++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

make
make  all-recursive
make[1]: Entering directory '/media/sanil/SanilED/Video/Twitter/vireo/vireo'
Making all in ../imagecore
make[2]: Entering directory '/media/sanil/SanilED/Video/Twitter/vireo/imagecore'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /media/sanil/SanilED/Video/Twitter/vireo/imagecore/missing aclocal-1.15 
../m4/m4-ax_cxx_compile_stdcxx_11.m4:38: error: macro AX_CXX_COMPILE_STDCXX is not defined; is a m4 file missing?
/usr/share/aclocal/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
../m4/m4-ax_cxx_compile_stdcxx_11.m4:38: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal-1.15: error: echo failed with exit status: 1
Makefile:499: recipe for target 'aclocal.m4' failed
make[2]: *** [aclocal.m4] Error 1
make[2]: Leaving directory '/media/sanil/SanilED/Video/Twitter/vireo/imagecore'
Makefile:2087: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/media/sanil/SanilED/Video/Twitter/vireo/vireo'
Makefile:649: recipe for target 'all' failed
make: *** [all] Error 2

Can someone please let me know how I should resolve it? 

Thanks!

**Comment by canbal** [comment] 2017-12-17 01:26
> ../m4/m4-ax_cxx_compile_stdcxx_11.m4:38: error: macro AX_CXX_COMPILE_STDCXX is not defined; is a m4 file missing?

Looks like an issue with your m4 setup. Can you try

`sudo apt-get install build-essential m4`

**Comment by sanilraut** [comment] 2017-12-17 01:50
Still see the same issue. 

sudo apt-get install build-essential m4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
m4 is already the newest version (1.4.17-5).
The following packages were automatically installed and are no longer required:
  fonts-lato gccgo-6 gpac-modules-base i965-va-driver:i386 liba52-0.7.4:i386 libaacs0:i386 libass5:i386 libavc1394-0:i386 libbdplus0:i386 libbluray1:i386 libbs2b0:i386 libcaca0:i386
  libcdio-cdda1:i386 libcdio-paranoia1:i386 libcdio13:i386 libcrystalhd3:i386 libcups2-dev libdc1394-22:i386 libdirectfb-extra libfaad2:i386 libflite1:i386 libfox-1.6-0 libfreenect0.5
  libfribidi0:i386 libgles1-mesa libgme0:i386 libgo9 libgomp1:i386 libgpac-dbg libgpac4 libgraphicsmagick-q16-3 libgsm1:i386 libiec61883-0:i386 libilmbase-dev libjasper-dev libjbig-dev
  libjpeg62:i386 libllvm3.8 libllvm3.8:i386 liblzma-dev libmad0:i386 libmodplug1:i386 libmp3lame0:i386 libnspr4:i386 libnuma1:i386 libopencore-amrnb0:i386 libopencore-amrwb0:i386
  libopencv-calib3d-dev libopencv-core-dev libopencv-core2.4v5:i386 libopencv-features2d-dev libopencv-flann-dev libopencv-gpu-dev libopencv-gpu2.4v5 libopencv-imgproc-dev
  libopencv-imgproc2.4v5:i386 libopencv-ml-dev libopencv-photo-dev libopencv-photo2.4v5 libopencv-stitching-dev libopencv-stitching2.4v5 libopencv-video-dev libopenexr-dev libopenjpeg5:i386
  libproxy-tools libqt5positioning5 libraw1394-11:i386 librtmp1:i386 libsamplerate0:i386 libschroedinger-1.0-0:i386 libsdl-image1.2 libsdl1.2debian:i386 libshine3:i386 libslang2:i386
  libsnappy1v5:i386 libsodium18:i386 libsoxr0:i386 libspeex1:i386 libspeexdsp1:i386 libssh-gcrypt-4:i386 libtbb2:i386 libtiffxx5 libtwolame0:i386 libusb-1.0-0:i386 libva1:i386
  libvdpau1:i386 libvlc5 libvlccore8 libvncserver-config libvo-aacenc0:i386 libvo-amrwbenc0:i386 libvpx3:i386 libwavpack1:i386 libwebp-dev libwebp5:i386 libwebpdemux1 libx264-148:i386
  libx265-79:i386 libxcb-shape0:i386 libxine2-doc libxvidcore4:i386 libzmq5:i386 libzvbi0:i386 linux-headers-4.4.0-101 linux-headers-4.4.0-101-generic linux-headers-4.4.0-103
  linux-headers-4.4.0-103-generic linux-headers-4.4.0-24 linux-headers-4.4.0-24-generic linux-headers-4.4.0-47 linux-headers-4.4.0-47-generic linux-headers-4.4.0-51
  linux-headers-4.4.0-51-generic linux-headers-4.4.0-59 linux-headers-4.4.0-59-generic linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-headers-4.4.0-64
  linux-headers-4.4.0-64-generic linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-71 linux-headers-4.4.0-71-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-headers-4.4.0-75 linux-headers-4.4.0-75-generic linux-headers-4.4.0-78 linux-headers-4.4.0-78-generic linux-headers-4.4.0-79
  linux-headers-4.4.0-79-generic linux-headers-4.4.0-81 linux-headers-4.4.0-81-generic linux-headers-4.4.0-83 linux-headers-4.4.0-83-generic linux-headers-4.4.0-87
  linux-headers-4.4.0-87-generic linux-headers-4.4.0-89 linux-headers-4.4.0-89-generic linux-headers-4.4.0-91 linux-headers-4.4.0-91-generic linux-headers-4.4.0-92
  linux-headers-4.4.0-92-generic linux-headers-4.4.0-93 linux-headers-4.4.0-93-generic linux-headers-4.4.0-96 linux-headers-4.4.0-96-generic linux-headers-4.4.0-97
  linux-headers-4.4.0-97-generic linux-headers-4.4.0-98 linux-headers-4.4.0-98-generic linux-image-4.4.0-101-generic linux-image-4.4.0-103-generic linux-image-4.4.0-21-generic
  linux-image-4.4.0-24-generic linux-image-4.4.0-47-generic linux-image-4.4.0-51-generic linux-image-4.4.0-59-generic linux-image-4.4.0-62-generic linux-image-4.4.0-64-generic
  linux-image-4.4.0-66-generic linux-image-4.4.0-71-generic linux-image-4.4.0-72-generic linux-image-4.4.0-75-generic linux-image-4.4.0-78-generic linux-image-4.4.0-79-generic
  linux-image-4.4.0-81-generic linux-image-4.4.0-83-generic linux-image-4.4.0-87-generic linux-image-4.4.0-89-generic linux-image-4.4.0-91-generic linux-image-4.4.0-92-generic
  linux-image-4.4.0-93-generic linux-image-4.4.0-96-generic linux-image-4.4.0-97-generic linux-image-4.4.0-98-generic linux-image-extra-4.4.0-101-generic linux-image-extra-4.4.0-103-generic
  linux-image-extra-4.4.0-21-generic linux-image-extra-4.4.0-24-generic linux-image-extra-4.4.0-47-generic linux-image-extra-4.4.0-51-generic linux-image-extra-4.4.0-59-generic
  linux-image-extra-4.4.0-62-generic linux-image-extra-4.4.0-64-generic linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-71-generic linux-image-extra-4.4.0-72-generic
  linux-image-extra-4.4.0-75-generic linux-image-extra-4.4.0-78-generic linux-image-extra-4.4.0-79-generic linux-image-extra-4.4.0-81-generic linux-image-extra-4.4.0-83-generic
  linux-image-extra-4.4.0-87-generic linux-image-extra-4.4.0-89-generic linux-image-extra-4.4.0-91-generic linux-image-extra-4.4.0-92-generic linux-image-extra-4.4.0-93-generic
  linux-image-extra-4.4.0-96-generic linux-image-extra-4.4.0-97-generic linux-image-extra-4.4.0-98-generic linux-signed-image-4.4.0-101-generic linux-signed-image-4.4.0-103-generic
  linux-signed-image-4.4.0-21-generic linux-signed-image-4.4.0-24-generic linux-signed-image-4.4.0-47-generic linux-signed-image-4.4.0-51-generic linux-signed-image-4.4.0-59-generic
  linux-signed-image-4.4.0-62-generic linux-signed-image-4.4.0-64-generic linux-signed-image-4.4.0-66-generic linux-signed-image-4.4.0-71-generic linux-signed-image-4.4.0-72-generic
  linux-signed-image-4.4.0-75-generic linux-signed-image-4.4.0-78-generic linux-signed-image-4.4.0-79-generic linux-signed-image-4.4.0-81-generic linux-signed-image-4.4.0-83-generic
  linux-signed-image-4.4.0-87-generic linux-signed-image-4.4.0-89-generic linux-signed-image-4.4.0-91-generic linux-signed-image-4.4.0-92-generic linux-signed-image-4.4.0-93-generic
  linux-signed-image-4.4.0-96-generic linux-signed-image-4.4.0-97-generic linux-signed-image-4.4.0-98-generic mesa-vdpau-drivers:i386 opencv-data qml-module-qt-labs-folderlistmodel
  qml-module-qt-labs-settings qml-module-qtwebkit qml-module-ubuntu-onlineaccounts qtdeclarative5-accounts-plugin qtdeclarative5-qtquick2-plugin rake ruby-did-you-mean ruby-minitest
  ruby-net-telnet ruby-power-assert ruby-test-unit snap-confine ubuntu-core-launcher va-driver-all:i386 vdpau-driver-all:i386 vdpau-va-driver:i386 vlc-data vlc-plugin-notify
  vlc-plugin-samba

**Comment by canbal** [comment] 2017-12-17 03:19
Do you have `autoconf` installed?

`sudo apt-get install autoconf`

**Comment by sanilraut** [comment] 2017-12-17 04:57
Yes autoconf is installed.

sudo apt-get install autoconf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).

**Comment by canbal** [comment] 2017-12-17 05:01
Unfortunately I'm unable to reproduce the same error so I'm going by my hunch. Can you try running these

`aclocal`
`autoconf`

and repeat the `configure` etc instructions

**Comment by sanilraut** [comment] 2017-12-17 08:16
Was able to resolve this issue by renaming
 m4-ax_cxx_compile_stdcxx_11.m4 to m4_ax_cxx_compile_stdcxx_11.m4 in the m4 folder.

Are you able to build using  m4-ax_cxx_compile_stdcxx_11.m4?

**Comment by canbal** [comment] 2017-12-17 23:21
That's interesting. Yes, it works on my Mac and I was able to on an Ubuntu Docker container as well.

I tried the renamed version and that works for me as well. Can you confirm this patch fixes it for you?

https://github.com/twitter/vireo/compare/m4?expand=1

**Comment by sanilraut** [comment] 2017-12-18 20:23
Yes the patch works for me. 
Thanks

**Comment by canbal** [comment] 2017-12-18 20:39
Great, merged.

**Closed** 2017-12-18 20:39 UTC
Labels: bug
